#!/usr/bin/env python3
"""Render manuscript tables directly from the validated Round 6 JSON."""

from __future__ import annotations

import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
PAPER = ROOT / "PaperDraft"
METHODS = (
    ("semantic_ucc", "semantic UCC"),
    ("qiskit_opt3", "\\texttt{qiskit opt3}"),
    ("pyzx_full_reduce", "PyZX \\texttt{full\\_reduce}"),
    ("tket_paulisimp_rebased", "TKET PauliSimp (rebased)"),
    ("staq_rotation_folding", "\\textbf{staq rotation folding}"),
    ("tket_guided_paulisimp", "TKET GuidedPauliSimp"),
)


def cell(row: dict) -> str:
    status = row["status"]
    if status == "completed":
        return f"{row['gate_count']}/{row['depth']}/{row['cx_count']}"
    if status == "timeout":
        return "timeout"
    if status == "predicate_error":
        return "predicate error"
    if status == "unsupported_conversion":
        return "unsupported"
    if status == "correctness_failure":
        return "correctness failure"
    return status.replace("_", " ")


def render(rows: list[dict], family: str, label: str, caption: str) -> str:
    selected = [row for row in rows if row["family_key"] == family]
    by_key = {(row["requested_gates"], row["method_key"]): row for row in selected}
    lines = [
        "% Generated by research/round6_major_revision/render_round6_tables.py",
        "\\begin{table*}[tbp]",
        "\\centering",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{@{}rrllllll@{}}",
        "\\toprule",
        "Requested & Actual & " + " & ".join(name for _, name in METHODS) + " \\\\",
        "\\midrule",
    ]
    for size in sorted({row["requested_gates"] for row in selected}):
        actual = next(row["actual_input_gates"] for row in selected if row["requested_gates"] == size)
        size_text = f"{size:,}".replace(",", "{,}")
        actual_text = f"{actual:,}".replace(",", "{,}")
        values = [cell(by_key[(size, method)]) for method, _ in METHODS]
        lines.append(f"{size_text} & {actual_text} & " + " & ".join(values) + " \\\\")
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}%",
            "}",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
            "\\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    rows = json.loads((HERE / "round6_all_results.json").read_text(encoding="utf-8"))
    unbounded = render(
        rows,
        "unbounded_independent_pauli",
        "tab:unbounded-witness",
        "Uniform-600 s comparison on the irrational independent-Pauli witness. Completed cells report gates/depth/\\texttt{cx}; other entries are status outcomes and are not scored as structural wins. The exact rank and irrational-angle certificate, rather than this numerical table, instantiate Theorem~\\ref{thm:final-output}. The public generic method is emphasized in the header.",
    )
    rational = render(
        rows,
        "rational_cp",
        "tab:fourier-phase-sandwich",
        "Uniform-600 s comparison on the rational CP finite-range witness. Completed cells report gates/depth/\\texttt{cx}; other entries are status outcomes and are not scored as structural wins. The family is certified only for $R<T=131040$, with per-transducer tail constants. No external row is a formal theorem instance. The public generic method is emphasized in the header.",
    )
    (PAPER / "round6_unbounded_table.tex").write_text(unbounded, encoding="utf-8")
    (PAPER / "round6_rational_table.tex").write_text(rational, encoding="utf-8")
    print("PaperDraft/round6_unbounded_table.tex")
    print("PaperDraft/round6_rational_table.tex")


if __name__ == "__main__":
    main()
