#!/usr/bin/env python3
"""Build all submission tables and numeric macros from canonical frozen data."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pandas as pd
import yaml


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "PaperDraft/generated"
MAP = ROOT / "data/provenance_map.yaml"


def load_source(relative: str) -> Any:
    path = ROOT / relative
    if path.suffix == ".parquet":
        return pd.read_parquet(path)
    if path.suffix == ".csv":
        return pd.read_csv(path)
    if path.suffix == ".json":
        return json.loads(path.read_text())
    raise ValueError(f"unsupported source: {relative}")


def select(frame: pd.DataFrame, selector: dict[str, Any]) -> pd.DataFrame:
    result = frame
    for key, value in selector.items():
        result = result[result[key] == value]
    return result


def evaluate(entry: dict[str, Any]) -> float | int:
    source = load_source(entry["source"])
    operation = entry["operation"]
    if operation == "row_count":
        return len(source)
    if operation == "value_count":
        return int((source[entry["column"]] == entry["value"]).sum())
    if operation == "true_count":
        series = source[entry["column"]]
        if series.dtype == object:
            series = series.astype(str).str.lower().map({"true": True, "false": False})
        return int(series.fillna(False).astype(bool).sum())
    if operation == "json_path":
        value = source
        for key in entry["path"].split("."):
            value = value[key]
        return value
    if operation == "selected_value":
        rows = select(source, entry["selector"])
        if len(rows) != 1:
            raise ValueError(f"selector for {entry['id']} returned {len(rows)} rows")
        return rows.iloc[0][entry["column"]].item()
    if operation == "ratio":
        numerator = select(source, entry["numerator_selector"])
        denominator = select(source, entry["denominator_selector"])
        if len(numerator) != 1 or len(denominator) != 1:
            raise ValueError(f"ratio selector for {entry['id']} is not scalar")
        return float(numerator.iloc[0][entry["column"]]) / float(denominator.iloc[0][entry["column"]])
    raise ValueError(f"unsupported provenance operation: {operation}")


def format_value(value: float | int, style: str) -> str:
    if style == "comma_int":
        return f"{int(value):,}"
    if style == "fixed0":
        return f"{float(value):.0f}"
    if style == "fixed1":
        return f"{float(value):.1f}"
    return str(value)


def tex_escape(value: Any) -> str:
    return str(value).replace("_", r"\_").replace("%", r"\%")


def write_numbers() -> list[dict[str, Any]]:
    provenance = yaml.safe_load(MAP.read_text())
    rows = []
    lines = ["% Generated by scripts/build_all_tables.py; do not edit."]
    for entry in provenance["entries"]:
        value = evaluate(entry)
        expected = entry["expected"]
        if isinstance(expected, float):
            if abs(float(value) - expected) > max(1e-10, abs(expected) * 1e-10):
                raise ValueError(f"provenance drift for {entry['id']}: {value} != {expected}")
        elif int(value) != int(expected):
            raise ValueError(f"provenance drift for {entry['id']}: {value} != {expected}")
        rendered = format_value(value, entry.get("format", "raw"))
        lines.append(rf"\newcommand{{\{entry['macro']}}}{{\DataNumber{{{entry['id']}}}{{{rendered}}}}}")
        rows.append({**entry, "observed": value, "rendered": rendered})
    (OUT / "paper_numbers.tex").write_text("\n".join(lines) + "\n")
    (ROOT / "data/frozen/paper_numbers.json").write_text(json.dumps(rows, indent=2, sort_keys=True) + "\n")
    return rows


def write_overview() -> None:
    rows = [
        ("W3: tradeoff traces", r"\TradeoffRuns", "all completed; no theorem-model mismatch"),
        ("W4: matched representations", r"\MatchedCells", r"\MatchedCompleted\ completed-valid; 15 predicate errors"),
        ("W5: external baselines", r"\ExternalCells", r"\ExternalCompleted\ completed-valid; 33 predicate errors"),
        ("W6: certificate mutations", r"\CertificateMutationCases", r"\CertificateFalseAccepts\ false accepts"),
        ("W7: fixed-error QRE", r"\QRECells", "all completed-valid"),
        ("W8: natural factorial", r"\NaturalCells", "all completed-valid"),
    ]
    body = "\n".join(f"{a} & {b} & {c} \\\\" for a, b, c in rows)
    (OUT / "results_overview.tex").write_text("% Generated from frozen data.\n" + body + "\n")


def write_qre() -> None:
    frame = pd.read_csv(ROOT / "data/frozen/qre_summary.csv")
    labels = {
        "semantic_first": "Semantic-first reference",
        "materialize_first": "Materialize-first",
        "external_tket_paulisimp": "External semantic-capable (TKET)",
    }
    lines = []
    for _, row in frame.sort_values("pipeline_id").iterrows():
        lines.append(
            f"{labels[row.pipeline_id]} & {int(row.logical_rotations):,} & {int(row.logical_t_states):,} & "
            f"{int(row.physical_qubits):,} & {int(row.factories)} & {int(row.cycles):,} & "
            f"{row.spacetime_qubit_seconds:.3g} \\\\"
        )
    (OUT / "qre_main_slice.tex").write_text("% Generated from data/frozen/qre_summary.csv.\n" + "\n".join(lines) + "\n\\bottomrule\n")


def write_natural() -> None:
    summary = pd.read_csv(ROOT / "data/frozen/natural_workload_summary.csv")
    positive = summary[summary.workload_class == "natural_positive"].sort_values("workload")
    lines = []
    for _, row in positive.iterrows():
        lines.append(
            f"{tex_escape(row.workload)} & {row.gates_external_minus_authors_mean:.1f} "
            f"[{row.gates_external_minus_authors_ci95_low:.1f}, {row.gates_external_minus_authors_ci95_high:.1f}] & "
            f"{'yes' if bool(row.predeclared_positive_family_success) else 'no'} \\\\"
        )
    (OUT / "natural_families.tex").write_text("% Generated from data/frozen/natural_workload_summary.csv.\n" + "\n".join(lines) + "\n\\bottomrule\n")

    effects = pd.read_csv(ROOT / "data/frozen/natural_ablation_effects.csv")
    effects = effects[(effects.workload_class == "natural_positive") & (effects.metric == "gates")]
    effect_lines = [
        f"{tex_escape(row.factor)} & {row['mean']:.1f} & [{row.ci95_low:.1f}, {row.ci95_high:.1f}] \\\\"
        for _, row in effects.iterrows()
    ]
    (OUT / "ablation_gate_effects.tex").write_text("% Generated from data/frozen/natural_ablation_effects.csv.\n" + "\n".join(effect_lines) + "\n\\bottomrule\n")


def write_manifest(outputs: list[Path]) -> None:
    records = {}
    for path in outputs:
        records[str(path.relative_to(ROOT))] = {
            "bytes": path.stat().st_size,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        }
    (OUT / "table_build_manifest.json").write_text(json.dumps({"schema": "ucc.table-build.v1", "outputs": records}, indent=2, sort_keys=True) + "\n")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = write_numbers()
    write_overview()
    write_qre()
    write_natural()
    outputs = [OUT / name for name in (
        "paper_numbers.tex", "results_overview.tex", "qre_main_slice.tex",
        "natural_families.tex", "ablation_gate_effects.tex",
    )] + [ROOT / "data/frozen/paper_numbers.json"]
    write_manifest(outputs)
    print(json.dumps({"numbers": len(rows), "outputs": [str(path) for path in outputs]}, indent=2))


if __name__ == "__main__":
    main()
